apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  labels:
    app: kiali
    version: master
data:
  config.yaml: |
    server:
      port: 20001
      static_content_root_directory: /opt/kiali/console
